### ISSUE TITLE
Single cell RNA-seq

### ISSUE THREAD

**Issue by alfonsosaera** [Cibiv/trumicount#1]
Dear Florian G. Pflug and Arndt von Haeseler,

I found your paper https://academic.oup.com/bioinformatics/advance-article/doi/10.1093/bioinformatics/bty283/4972993 and find it very interesting and useful.

I am working with UMI-Tools and single cell RNA-seq data that contains UMIs following this tutorial https://github.com/CGATOxford/UMI-tools/blob/master/doc/Single_cell_tutorial.md from UMI-tools site. For the Counting UMIs per gene step it uses:

umi_tools count --per-gene --gene-tag=XT --per-cell -I assigned_sorted.bam -S counts.tsv.gz

so Reads will only be grouped together if they have the same cell barcode and are mapped to the same gene.

In your manual says that "TRUmiCount uses UMI-Tools’ “group” tool to extract a list of UMIs and their read counts from the specified BAM file".

How could I use the --per-gene and --per-cell options with TRUmiCount?

Thanks for your help. I look forward hearing from you.

Alfonso

**Comment by fgp** [comment]
There are multiple ways to do this.

You can either manually run UMI-Tools `group` tool (i.e. `umi_tools group ...`) with the desired options to produce a list of reads grouped per UMI. You can then use `trumicount --input-umitools-group-out` to process this list with TRUmiCount.

Or you can let TRUmiCount run UMI-Tools for you, and use `--umitools-option ...` to pass custom options to UMI-Tools. Note that to pass multiple options to UMI-Tools, you have to use `--umitools-option` multiple times, i.e. to pass the options `--per-gene --gene-tag=XT` you would use `--umitools-option --per-gene --umitools-option --gene-tag=XT`.

In additional to the input options, you will have to additional specify a read-count threshold to TRUmiCount using the option `--threshold ...`, and you should specify whether molecules were originally single- or double-stranded (`--molecules 1` or `--molecules 2`). To find a good error-correction threshold, I recommend you let TRUmiCount generate diagnostic plots with `--output-plots`, and compare the reads/UMI distribution plots for various thresholds to find one that yields a good fit, yet preserves a sensible fraction of UMIs. And you will want to use `--output-counts my_output.tab` to save the biases-corrected counts to a file.

Please be aware that I haven't done much testing of TRUmiCount in connection with UMI-Tools' `--per-cell` option yet, so it is possible that you may encounter bugs. Please let me know if things don't work as you'd expect!

**Comment by alfonsosaera** [comment]
Thanks for the quick answer and all the suggestions!

I will try and let you know how it goes.

**Comment by alfonsosaera** [comment]
Hi, 

I tried both suggestions with different results:

A) let TRUmiCount run UMI-Tools
**** 1 ********
Modified from manual (https://cibiv.github.io/trumicount/manual.pdf) 4.1 Single-End Data.
COMMAND: 
$ trumicount --input-bam  $samplePATH/assigned_sorted.bam \
                   --molecules 1 --threshold 2 \
                   --umitools-option --per-gene \
                   --umitools-option --gene-tag=XT \
                   --umitools-option --per-cell \
                   --output-plots $outputPATH/SRR3472973.pdf --plot-hist-bin 1 \
                   --plot-var-bins 20 --plot-var-logy \
                   --output-counts $outputPATH/SRR3472973.tab \
                   --cores 20

assigned_sorted.bam is generated following the cell RNA-seq tutorial (https://github.com/CGATOxford/UMI-tools/blob/master/doc/Single_cell_tutorial.md) from UMI-tools site --> Mapping reads with STAR and Assigning mapped reads to genes with featureCounts.

OUTPUT:
Error: 
 usage: trumicount (--input-bam INBAM | --input-umitools-group-out GROUPSINTAB | --input-umis UMISINTAB) [options]
Execution interrupted

adding --verbose did not provide more info about the error

**** 2 ********
same as before but removing all UMI-tools options
COMMAND:
$ trumicount --input-bam  $samplePATH/assigned_sorted.bam \
                   --molecules 1 --threshold 2 \
                   --output-plots $outputPATH/SRR3472973.pdf --plot-hist-bin 1 \
                   --plot-var-bins 20 --plot-var-logy \
                   --output-counts $outputPATH/SRR3472973.tab \
                   --verbose --cores 20

OUTPUT:
$`Command Line Arguments`
List of 57
 $ --input-bam               : chr "/media/sequentia/synology_office/projects/250-Alfonso/output_UMI_backbone_pancreas_full_96cells/SRR3472973/STAR"| __truncated__
 $ --input-umitools-group-out: NULL
 $ --input-umis              : NULL
 $ --output-counts           : chr "/media/sequentia/synology_office/projects/250-Alfonso/TRUmiCount_output3/SRR3472973.tab"
 $ --output-umis             : NULL
 $ --output-final-umis       : NULL
 $ --output-plots            : chr "/media/sequentia/synology_office/projects/250-Alfonso/TRUmiCount_output3/SRR3472973.pdf"
 $ --output-genewise-fits    : NULL
 $ --umitools                : chr "umi_tools"
 $ --umitools-option         : NULL
 $ --umi-sep                 : chr ":"
 $ --umipair-sep             : chr ""
 $ --paired                  : logi FALSE
 $ --mapping-quality         : chr "20"
 $ --filter-strand-umis      : logi FALSE
 $ --combine-strand-umis     : logi FALSE
 $ --threshold               : chr "2"
 $ --molecules               : chr "1"
 $ --genewise-min-umis       : chr "5"
 $ --cores                   : chr "20"
 $ --variance-estimator      : chr "lsq"
 $ --digits                  : chr "3"
 $ --plot-hist-bin           : chr "1"
 $ --plot-hist-xmax          : NULL
 $ --plot-skip-phantoms      : logi FALSE
 $ --plot-var-bins           : chr "20"
 $ --plot-var-logy           : logi TRUE
 $ --verbose                 : logi TRUE
 $ input-bam                 : chr "/media/sequentia/synology_office/projects/250-Alfonso/output_UMI_backbone_pancreas_full_96cells/SRR3472973/STAR"| __truncated__
 $ input-umitools-group-out  : NULL
 $ input-umis                : NULL
 $ output-counts             : chr "/media/sequentia/synology_office/projects/250-Alfonso/TRUmiCount_output3/SRR3472973.tab"
 $ output-umis               : NULL
 $ output-final-umis         : NULL
 $ output-plots              : chr "/media/sequentia/synology_office/projects/250-Alfonso/TRUmiCount_output3/SRR3472973.pdf"
 $ output-genewise-fits      : NULL
 $ umitools                  : chr "umi_tools"
 $ umitools-option           : NULL
 $ umi-sep                   : chr ":"
 $ umipair-sep               : chr ""
 $ paired                    : logi FALSE
 $ mapping-quality           : int 20
 $ filter-strand-umis        : logi FALSE
 $ combine-strand-umis       : logi FALSE
 $ threshold                 : int 2
 $ molecules                 : int 1
 $ genewise-min-umis         : chr "5"
 $ cores                     : int 20
 $ variance-estimator        : chr "lsq"
 $ digits                    : int 3
 $ plot-hist-bin             : int 1
 $ plot-skip-phantoms        : logi FALSE
 $ plot-var-bins             : num 20
 $ plot-var-logy             : logi TRUE
 $ verbose                   : logi TRUE
 $ strand-umis               : logi FALSE
 $ var-est-distfree          : logi TRUE
NULL

*** Loading library `parallel` to allow computations on 20 cores
*** Will use umi_tools to extract UMIs from /media/sequentia/synology_office/projects/250-Alfonso/output_UMI_backbone_pancreas_full_96cells/SRR3472973/STAR_alignment/assigned_sorted.bam
*** Reading UMIs
Command: 'umi_tools' group --group-out /dev/stdout -I '/media/sequentia/synology_office/projects/250-Alfonso/output_UMI_backbone_pancreas_full_96cells/SRR3472973/STAR_alignment/assigned_sorted.bam' -L /dev/stderr --umi-sep ':'  --mapping-quality 20  |
         gawk 'BEGIN {gidp=-1;numis=1;lp="";umip="";FS="\t";print "gene" "\t" "sample" "\t" "pos" "\t" "end" "\t" "umi" "\t" "rawumis" "\t" "reads";}NR==1 {Iread_id=Icontig=Iposition=Iposition2=Igene=Iumi=Iumi_count=Ifinal_umi=Ifinal_umi_count=Iunique_id=-1;for (i=1;i<=NF;i++) {switch ($i) {case "read_id": Iread_id=i; break;case "contig": Icontig=i; break;case "position": Iposition=i; break;case "position2": Iposition2=i; break;case "gene": Igene=i; break;case "umi": Iumi=i; break;case "umi_count": Iumi_count=i; break;case "final_umi": Ifinal_umi=i; break;case "final_umi_count": Ifinal_umi_count=i; break;case "unique_id": Iunique_id=i; break;}}}NR>1 {l=$0;gid=$Iunique_id;umi=$Iumi;if (gidp==-1) {}else if (gid!=gidp) {$0=lp;print ($Igene=="NA"?$Icontig:$Igene) "\t" "" "\t" $Iposition "\t" (Iposition2>0?$Iposition2:"NA") "\t" $Ifinal_umi "\t" numis "\t" $Ifinal_umi_count;numis=1;}else if (umi!=umip) {numis+=1;}lp=l;gidp=gid;umip=umi}END {$0=lp;print ($Igene=="NA"?$Icontig:$Igene) "\t" "" "\t" $Iposition "\t" (Iposition2>0?$Iposition2:"NA") "\t" $Ifinal_umi "\t" numis "\t" $Ifinal_umi_count;}'

# output generated by group --group-out /dev/stdout -I /media/sequentia/synology_office/projects/250-Alfonso/output_UMI_backbone_pancreas_full_96cells/SRR3472973/STAR_alignment/assigned_sorted.bam -L /dev/stderr --umi-sep : --mapping-quality 20
# job started at Tue May  1 20:14:15 2018 on eurk-126-93.uab.es -- 536838be-6c97-44a9-8539-dfab2abdfcb2
# pid: 17692, system: Linux 3.10.0-693.el7.x86_64 #1 SMP Tue Aug 22 21:09:27 UTC 2017 x86_64
# cell_tag                                : None
# cell_tag_delim                          : None
# cell_tag_split                          : -
# chrom                                   : None
# compresslevel                           : 6
# detection_method                        : None
# gene_tag                                : None
# gene_transcript_map                     : None
# get_umi_method                          : read_id
# ignore_umi                              : False
# in_sam                                  : False
# log2stderr                              : False
# loglevel                                : 1
# mapping_quality                         : 20
# method                                  : directional
# no_sort_output                          : False
# out_sam                                 : False
# output_bam                              : False
# output_unmapped                         : False
# paired                                  : False
# per_cell                                : False
# per_contig                              : False
# per_gene                                : False
# random_seed                             : None
# read_length                             : False
# short_help                              : None
# skip_regex                              : ^[__|Unassigned]
# soft_clip_threshold                     : 4
# spliced                                 : False
# stderr                                  : <open file '<stderr>', mode 'w' at 0x7fb8b84b21e0>
# stdin                                   : <open file '/media/sequentia/synology_office/projects/250-Alfonso/output_UMI_backbone_pancreas_full_96cells/SRR3472973/STAR_alignment/assigned_sorted.bam', mode 'r' at 0x4443c00>
# stdlog                                  : <open file '/dev/stderr', mode 'a' at 0x402d300>
# stdout                                  : <open file '<stdout>', mode 'w' at 0x7fb8b84b2150>
# subset                                  : None
# threshold                               : 1
# timeit_file                             : None
# timeit_header                           : None
# timeit_name                             : all
# tsv                                     : /dev/stdout
# umi_group_tag                           : BX
# umi_sep                                 : :
# umi_tag                                 : RX
# umi_tag_delim                           : None
# umi_tag_split                           : None
# whole_contig                            : False
Traceback (most recent call last):
  File "/home/asaera/.local/bin/umi_tools", line 9, in <module>
    load_entry_point('umi-tools==0.5.3', 'console_scripts', 'umi_tools')()
  File "/home/asaera/.local/lib/python2.7/site-packages/umi_tools-0.5.3-py2.7-linux-x86_64.egg/umi_tools/umi_tools.py", line 59, in main
    module.main(sys.argv)
  File "/home/asaera/.local/lib/python2.7/site-packages/umi_tools-0.5.3-py2.7-linux-x86_64.egg/umi_tools/group.py", line 247, in main
    threshold=options.threshold)
  File "/home/asaera/.local/lib/python2.7/site-packages/umi_tools-0.5.3-py2.7-linux-x86_64.egg/umi_tools/network.py", line 372, in __call__
    min(len_umis), max(len_umis)))
AssertionError: not all umis are the same length(!):  32 - 33
Found 3 UMIs for 1 genes in 1 samples after grouping of similar UMIs
*** Filtering UMIs with fewer than 2 reads
0 UMIs remained for 1 genes in 0 samples after applying filters
Error: Too few UMIs to continue
Execution interrupted

**** 3 ********
same as number 1 but without --per-cell option
COMMAND: 
$ trumicount --input-bam  $samplePATH/assigned_sorted.bam \
                   --molecules 1 --threshold 2 \
                   --umitools-option --per-gene \
                   --umitools-option --gene-tag=XT \
                   --umitools-option --per-cell \
                   --output-plots $outputPATH/SRR3472973.pdf --plot-hist-bin 1 \
                   --plot-var-bins 20 --plot-var-logy \
                   --output-counts $outputPATH/SRR3472973.tab \
                   --cores 20

OUTPUT:
Error: 
 usage: trumicount (--input-bam INBAM | --input-umitools-group-out GROUPSINTAB | --input-umis UMISINTAB) [options]
Execution interrupted

B)  manually run UMI-Tools group tool
**** 4 ********
$ umi_tools group --per-gene --gene-tag=XT --per-cell \
  --output-bam -S  $outputPATH/output.bam \
  -I $samplePATH/assigned_sorted.bam \
  --group-out=$outputPATH/SRR3472973.tsv.gz

Here I check the output of UMI-Tools group:
$ zcat SRR3472973.tsv.gz | head
read_id	                           contig   position	           gene	 umi	umi_count	final_umi	final_umi_count	unique_id
SRR3472973.15468604_CGGATGAT_GGGG	      1  169851414	ENSG00000000457	GGGG	        2	     GGGG	              2	        0
SRR3472973.380923_CGGATGAT_GGGG	        1	 169851414	ENSG00000000457	GGGG	        2	     GGGG	              2	        0
SRR3472973.8427344_CGTGTGAG_CTAT      	1  169849958	ENSG00000000457	CTAT	        4	     CTAT	              4	        1
SRR3472973.11544762_CGTGTGAG_CTAT     	1  169849958	ENSG00000000457	CTAT	        4	     CTAT	              4	        1
SRR3472973.10374759_CGTGTGAG_CTAT     	1  169849958	ENSG00000000457	CTAT	        4	     CTAT	              4	        1
SRR3472973.16148546_CGTGTGAG_CTAT     	1  169849958	ENSG00000000457	CTAT	        4	     CTAT	              4	        1
SRR3472973.1071742_CAGTCCGA_GGTG      	1  196747284	ENSG00000000971	GGTG	        2	     GGTG	              2	        2
SRR3472973.10343459_CAGTCCGA_GGTG     	1  196747353	ENSG00000000971	GGTG	        2	     GGTG	              2	        2
SRR3472973.14770118_CATCATCC_GGTG     	1  196737490	ENSG00000000971	GGTG	       37	     GGTG	             38	        3

$ zcat SRR3472973.tsv.gz | grep _GGGG | head
SRR3472973.15468604_CGGATGAT_GGGG	1	169851414	ENSG00000000457	GGGG	2	GGGG	2	 0
SRR3472973.380923_CGGATGAT_GGGG 	1	169851414	ENSG00000000457	GGGG	2	GGGG	2	 0
SRR3472973.639105_GCTTGGAG_GGGG	  1	196747204	ENSG00000000971	GGGG	4	GGGG	4	 6
SRR3472973.6244825_GCTTGGAG_GGGG	1	196747204	ENSG00000000971	GGGG	4	GGGG	4	 6
SRR3472973.7822867_GCTTGGAG_GGGG	1	196747204	ENSG00000000971	GGGG	4	GGGG	4	 6
SRR3472973.17122473_GCTTGGAG_GGGG	1	196747204	ENSG00000000971	GGGG	4	GGGG	4	 6
SRR3472973.17791453_ATGTGGAG_GGGG	1	 24358482	ENSG00000001460	GGGG	1	GGGG	1	10
SRR3472973.9254876_CGGATCGA_GGGG	1	 24357165	ENSG00000001460	GGGG	3	GGGG	3	11
SRR3472973.6432708_CGGATCGA_GGGG	1	 24357165	ENSG00000001460	GGGG	3	GGGG	3	11
SRR3472973.10614325_CGGATCGA_GGGG	1	 24357413	ENSG00000001460	GGGG	3	GGGG	3	11

It appears that correctly identifies the different umis in different cells (pipeline with grep)

$ trumicount --input-umitools-group-out $outputPATH/SRR3472973.tsv.gz \
                   --molecules 1 --threshold 2 \
                   --output-plots $outputPATH/SRR3472973.pdf --plot-hist-bin 1 \
                   --plot-var-bins 20 --plot-var-logy \
                   --output-counts $outputPATH/SRR3472973.tab \
                   --cores 20

check trumicount tab file
$ head SRR3472973.tab 
sample	gene	            n.umis	n.tot	efficiency	  depth	  loss	n.obs
	      ENSG00000000003	      25  37.81	  0.00e+00	  3.520	0.3388 	   25
	      ENSG00000000419	      18  23.11	  0.00e+00	  6.722	0.2211	   18
	      ENSG00000000457	       2   2.43	  0.00e+00	  9.861	0.1757	    2
	      ENSG00000000971	       8  10.17	  0.00e+00	  6.375	0.2133	    8
	      ENSG00000001036	      34  41.94	  0.00e+00	  8.853	0.1893	   34
	      ENSG00000001084	      18  24.14	  0.00e+00	  5.333	0.2542	   18
	      ENSG00000001167	       6   6.71	  3.44e-02	 11.400	0.1063	    6
	      ENSG00000001460	       6   6.98	  3.01e-02	  5.510	0.1408	    6
	      ENSG00000001461	      16  19.41	  0.00e+00	  9.875	0.1755	   16

I am not sure this is the desired result, I was expecting the sample column with cell info but it is empty

The pdf with the plots is attached. Is this the expected result? Is there an option to modify the x axis limits?
[SRR3472973.pdf](https://github.com/Cibiv/trumicount/files/1964813/SRR3472973.pdf)


How could I get TRUmiCount to run UMI-tools so identified cells are properly recognized?

Thanks for your help and suggestions,

Alfonso

**Comment by fgp** [comment]
Dear Alfonso,

The main problem seem to be that `umi_tools`, even with the `--per-cell` option, doesn't report the cell barcode in the output of `umi_tools --group`. Or, more precisely, not in a format that TRUmiCount can read -- the cell barcode is included in the read_id, but not in a separate "sample" column. For the time being, you'll need to post-process the `umi_tools group` output to transform to extract the cell barcode from the read_id. Here is an AWK script that should do that:

```
BEGIN {
  FS = "\t"
}
NR==1{
  printf "%s\tcell", $1
  for(i=2; i<=NF; ++i)
    printf "\t%s", $i
  printf "\n"
}
NR>1 {
  printf "%s\t%s", $1, gensub(/^.*_([ACGTNacgtn]+)_([ACGTNacgtn]+)$/, "\\1", "g", $1)
  for(i=2; i<=NF; ++i)
    printf "\t%s", $i
  printf "\n"
}
```

If you save that script to `extract_cell_barcode.awk`, you can transform the `umi_tools group` output with
```
  awk -f extract_cell_barcode.awk < SRR3472973.tsv > SRR3472973.cell.tsv
```

There was also a bug in TRUmiCount that prevents it from reading the cell barcodes even if they appear in the file. I'm in the process of fixing that, and will push a new version of TRUmiCount to github hopefully later today. I will let you know when I did.

If possible, please send me the full output of `umi_tools --group`, this would allow me to test me fixed with your data. My e-mail address is "florian (dot) pflug (at) univie (dot) ac (dot) at".

**Comment by fgp** [comment]
In my previous reply I forgot to mention that you can adjust the scale of the x-axis in the histogram plot with `--plot-hist-xmax MAXIMUM_VALUE`. If the histogram is too course (i.e. bins are too large) after zooming, you can adjust the bin size as well with `--plot-hist-bin BIN_SIZE`

**Comment by alfonsosaera** [comment]
Hi Florian,

Thanks for the quick response and the script to post-process UMI-Tools output. I already sent you that file.

Reading your comments seems that, for now, I will have to use UMI-Tools + TRUmiCount instead of letting TRUmiCount do the job for me. Is that correct?

Thanks again for your help and interest!

**Comment by fgp** [comment]
Hi Alfonso,

Yes, for now I think it's simpler to separate things are much as possible and thus for you to run UMI-Tools separately. Once we've fleshed out the problem with the per-cell barcodes, I'll look into why using UMI-Tools through TRUmiCount didn't work for you.

Thanks for sending the `umi_tools group` output. I'll look into it ASAP.

best,
Florian

**Comment by alfonsosaera** [comment]
Hi Florian,

I tried TRUmiCount with the post-processing as you suggested. However the result is the same as using UMI-Tools output directly. I realize now you are working in a new commit, did you already push it?

I also modified the histogram following your suggestion, could you please take a look (attached) and let me know if you think the selected threshold is fine? 
[SRR3472973.pdf](https://github.com/Cibiv/trumicount/files/1970829/SRR3472973.pdf)

Thanks again!

Alfonso

**Comment by fgp** [comment]
Hi Alfonso,

I haven't pushed my TRUmiCount fixes yet, sorry. There is still a remaining problem when running TRUmiCount on your dataset - it looks like it hits a limitation in data.table. I'm currently trying to find a workaround , and once that problem is fixed, I'll push my fixes and notify you.

best,
Florian

**Comment by fgp** [comment]
Dear Alfonso,

I've new pushed a new version of TRUmiCount that should now read the cell barcodes correctly from the (modified) UMI-Tools group output. You will also need to update to the latest version of gwpcR (the actual workhorse behind TRUmiCount) -- version 0.9.9 is afflicted by a limitation of data.table, and fails for your dataset with "length -2103378759 is too large for hashing". You can install the new version directly from github (see https://github.com/Cibiv/gwpcR) or wait for the new version to appear on Bioconda (I've pushed it there as well, the package should be available within a day or so). I'll also push a new version of TRUmiCount to github shortly, but I noticed that the installation instructions in the manual are a bit out-dated and want to fix that first.

With these versions, the following command finished successfully for your dataset.

```
trumicount \
	--input-umitools-group-out SRR3472973.cell.tsv.gz \
	--molecules 1 --threshold 2 \
	--output-plots SRR3472973.pdf --plot-hist-bin 1 --plot-hist-xmax 50 \
	--plot-var-bins 20 --plot-var-logy \
	--output-counts SRR3472973.tab \
	--output-genewise-fits SRR3472973.full.tab \
	--cores 64
```

Regarding the threshold -- generally, it seems that your data-set shows even more dispersion of the read-count than our algorithm predicts. Not sure why that is the case. One possible reason is the that your UMIs are quite short - only 4 bases as far as I can see. With such short UMIs, it is likely that UMIs are re-used for transcripts of the same gene, which "spreads out" the per-UMI read counts in a way the TRUmiCount currently doesn't model, unfortunately, meaning that the "loss" is currently probably under-estimated by TRUmiCount.

In your last PDF, I believe that you increased `--molecules` from 1 to 2. Given that your data is alreadyy more spread out than TRUmiCount predicts, and that higher initial molecule counts *decrease* the variation of the read-count distribution, it's probably best to leave this at `1` at the moment. (The correct value depends on the library preparation protocol)

You might be interested to know that I do plan to investigate how to best include this effect in our model, but can't say yet when such an extended version might be available.

best,
Florian

**Comment by alfonsosaera** [comment]
Hi Florian,

Thanks for your help. Now it works smoothly.

Regarding increased `--molecules` from 1 to 2. You are right, I inadvertently removed `--molecules 1` from the code. This is also something I do not fully understand, the reads I am using were processed using cel-seq protocol, where UMIs and cell barcode are in read 1, but with no sequence to map against genome, and transcript sequence to map is in read 2. I understand that, for this type of data, I should use the  `--molecules 1` option. Should I? Also, could you provide an example of protocol that uses UMIs and requires  the `--molecules 2` option? Thank you.

Yes, the UMIs are only 4 nt long and therefore are most likely being reused, If I understood properly TRUmiCount does not model reusing UMIs for the same transcript but you have plans about it.

Regarding this dataset, as you can see in the attached histograms, most transcripts have only 1 UMI and therefore are considered phantom by TRUmiCount, is this right? I think that this UMI distribution is due to low coverage during sequencing. Would this mean that datasets with low coverage are not the best ones to be analyzed with TRUmiCount?

Thanks again for your help,

Alfonso

**Comment by fgp** [comment]
Dear Alfonso,

The `--molecules` option specifies how many template for each molecules are present at the beginning of the first PCR cycle. For the purpose of TRUmiCount, a *molecule* is thus a single strand of DNA, because strands are the *units* copies by the PCR. In other words, if you start with fully complementary double-stranded fragments, `--molecules 2` should be appropriate, otherwise `--molecules 1`. I briefly looked inot the CEL-Seq protocol as described by Hashimshony et al. (2012), "CEL-Seq: Single-Cell RNA-Seq by Multiplexed Linear Amplification", but have to admit that the protocol isn't completely clear to me, so I can't say how to best apply TRUmiCount. It seems to contain a linear amplification step, but I'm unclear on when that actually is supposed to happen - possibly during the 2nd transcription step. In your case, since the first is clearly better with `--molecules 1`, I recommend sticking with that for now.

I didn't see a histogram attached to your last post, but I general yes, if most UMIs are represented by only a single read, then filtering by read-count isn't really possible, and TRUmiCount is less usefull. TRUmiCount can still attempt to estimate the percentage of lost molecules though -- so long as there is still a reasonable number of UMIs with more than one read (a few hundred the least, better a few thousand), the read/count distribution still contains some useable information.

best,
Florian

PS: I'm leaving this bug report open since I'd like to make running UMI-Tools through TRUmiCount possible for your dataset, instead of having to run things separately.

**Comment by alfonsosaera** [comment]
Dear Florian,

Thanks for your help and useful explanations.

I would love to be able to run  UMI-Tools through TRUmiCount for datasets with cell-barcodes.

Best,

Alfonso

**Comment by fgp** [comment]
Dear Alfonso,

Would it be possible for you to send your BAM file (or a subset thereof)? That would allow me to test running UMI-Tools through TRUmiCount for your dataset. 

best,
Florian

**Comment by fgp** [comment]
Dear Alfonso,

I've now fixed things so that TRUmiCount can invoke UMI-Tools directoy for your dataset. For this to work, however, a version of UMI-Tools where the ``group`` tool  outputs the cell barcode in a separate column is required, in addition to TRUmiCount 0.9.11. With that version of TRUmiCount, the desired grouping/count level (i.e. per cell, per gene, or per combination of cell and gene) and now be chosen with the new `--group-per` option.

### Required version of UMI-Tools (0.5.3_tuc)
Our patched version of UMI-Tools with the additional output column can be installed from the ``cibiv`` channel for conda -- you can install it with

 ```
  consta install -c cibiv umitools_tuc
```

### Required version of TRUmiCount (0.9.11)
TRUmiCount 0.9.11, unfortunately, cannot yet be installed via Bioconda because Bioconda are the middle of updating their package building infrastructure to a new version, and have asked for now package updated to be done at the moment. You can, however, simply download the ZIP for 0.9.11 from https://github.com/Cibiv/trumicount/releases, extract it, and run the `trumicount' script it contains. If you had the previous version of TRUmiCount installed (via Bioconda or otherwise), the new version should run as well as it has the same set of dependencies.

### TRUmiCount Invocation

The following TRUmiCount command should then work.
```
trumicount \
	--input-bam SRR3472973.bam \
        --umitools-option --gene-tag=XT --umitools-option --per-gene \
	--group-per cell,gene --molecules 1 --threshold 2 \
	--output-plots SRR3472973.pdf --plot-hist-bin 1 --plot-hist-xmax 50 \
	--plot-var-bins 20 --plot-var-logy \
	--output-counts SRR3472973.tab \
	--cores 64 --verbose
```

I'm closing this issue for now, feel free to re-open this or another issue if you have further problems.
